# Generated by Django 3.0.3 on 2020-03-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='scale',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='measure',
            name='type',
            field=models.CharField(default='temperatura', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='value',
            field=models.IntegerField(default='0', verbose_name='valor'),
        ),
    ]
